name: Build main
on:
  push:
    branches:
      - main
jobs:
  build_main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4.2.2

    - name: Setup Java
      uses: actions/setup-java@v4.5.0
      with:
        distribution: 'temurin'
        java-version: 23

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4.2.1

    - name: Build
      run: ./gradlew build sourcesJar dokkaGeneratePublicationHtml publish
      env:
        ORG_GRADLE_PROJECT_githubActor: ${{ secrets.GITHUBACTOR }}
        ORG_GRADLE_PROJECT_githubToken: ${{ secrets.GITHUBTOKEN }}
